apiVersion: v1
kind: Pod
metadata:
  name: resource-exceeds-node-pod
spec:
  containers:
    - name: container-1
      image: nginx:latest
      resources:
        limits:
          memory: "8Gi"  # Exceeds node capacity
